### ISSUE TITLE
[FEATURE] Any plans to add a MultiBlocPresentationListener?

### ISSUE THREAD

**Issue by vaibhav-savii** [leancodepl/bloc_presentation#33]
Something similar to `MultiBlocListener` to avoid nesting in case of multiple cubit/bloc:

```
MultiBlocPresentationListener(
 listeners: [
     BlocPresentationListener<BlocA, BlocAEvent>(
       listener: (context, event) {},
     ),
     BlocPresentationListener<BlocB, BlocBEvent>(
       listener: (context, event) {},
     ),
     BlocPresentationListener<BlocC, BlocCEvent>(
       listener: (context, event) {},
     ),
   ],
   child: ChildA(),
 )
```

**Comment by shilangyu** [comment]
Sorry for the very late reply:

`BlocPresentationListener` implements the `nested` interfaces. So have a multi listener version it is enough that you use the `Nested` widget from `package:nested`:

```dart
Nested(
  children: [
    BlocPresentationListener<BlocA, BlocAEvent>(
      listener: (context, event) {},
    ),
    BlocPresentationListener<BlocB, BlocBEvent>(
      listener: (context, event) {},
    ),
    BlocPresentationListener<BlocC, BlocCEvent>(
      listener: (context, event) {},
    ),
  ],
  child: ChildA(),
)
```

In fact, this is exactly what `package:flutter_bloc` does. Except it provides a new type for this: https://github.com/felangel/bloc/blob/ac6ac74c306ea00ae1e263a714de8768c9662304/packages/flutter_bloc/lib/src/multi_bloc_listener.dart#L51 (it extends `MultiProvider`, but if you check what `MultiProvider` is, you will find it is a wrapper for `Nested`). IMO this is just a duplication of the API for no reason: you can use `Nested` for all nested-compliant classes. Thus please use `Nested`, I am not keen on adding `MultiBlocPresentationListener` as it does nothing as state above.
